export type Exercise =
  | { type: "choice"; prompt: string; question: string; options: string[]; answer: string; hint?: string }
  | { type: "translate"; prompt: string; from: string; to: string; answer: string; choices: string[] }
  | { type: "order"; prompt: string; french: string; words: string[]; answer: string[] }
  | { type: "match"; prompt: string; pairs: { fr: string; fon: string }[] };

export type Lesson = {
  id: string;
  title: string;
  emoji: string;
  exercises: Exercise[];
};

export type World = {
  id: string;
  title: string;
  subtitle: string;
  emoji: string;
  color: "primary" | "gold" | "coral";
  lessons: Lesson[];
};

export const worlds: World[] = [
  {
    id: "w1",
    title: "Premiers mots",
    subtitle: "Les salutations en Fɔngbè",
    emoji: "👋",
    color: "primary",
    lessons: [
      {
        id: "w1l1",
        title: "Bonjour & Merci",
        emoji: "☀️",
        exercises: [
          {
            type: "choice",
            prompt: "Nouveau mot",
            question: "Comment dit-on « Bonjour » en Fon ?",
            options: ["Aɖabɔ", "Mawu", "A fɔn ganji à ?", "Oɖabɔ"],
            answer: "A fɔn ganji à ?",
            hint: "Littéralement : « Es-tu bien réveillé ? »",
          },
          {
            type: "translate",
            prompt: "Traduire en Fon",
            from: "Merci",
            to: "fon",
            answer: "Awanou",
            choices: ["Awanou", "Eɛ", "Eo", "Mawu"],
          },
          {
            type: "choice",
            prompt: "Choisir la bonne réponse",
            question: "« Eɛ » signifie...",
            options: ["Non", "Oui", "Merci", "Bonjour"],
            answer: "Oui",
          },
          {
            type: "order",
            prompt: "Reconstruis la phrase",
            french: "Bonjour, comment vas-tu ?",
            words: ["A", "fɔn", "ganji", "à", "?"],
            answer: ["A", "fɔn", "ganji", "à", "?"],
          },
          {
            type: "match",
            prompt: "Associe les mots",
            pairs: [
              { fr: "Oui", fon: "Eɛ" },
              { fr: "Non", fon: "Eo" },
              { fr: "Merci", fon: "Awanou" },
              { fr: "Bonjour", fon: "Aɖabɔ" },
            ],
          },
        ],
      },
      {
        id: "w1l2",
        title: "Oui, Non, Au revoir",
        emoji: "💬",
        exercises: [
          {
            type: "choice",
            prompt: "Nouveau mot",
            question: "Comment dit-on « Non » en Fon ?",
            options: ["Eɛ", "Eo", "Awanou", "Mi"],
            answer: "Eo",
          },
          {
            type: "translate",
            prompt: "Traduire en français",
            from: "Eɛ",
            to: "fr",
            answer: "Oui",
            choices: ["Oui", "Non", "Merci", "Salut"],
          },
          {
            type: "choice",
            prompt: "Culture",
            question: "« Aɖabɔ » est utilisé...",
            options: ["Le matin", "Le soir", "À table", "À l'école"],
            answer: "Le matin",
            hint: "C'est la salutation matinale traditionnelle.",
          },
          {
            type: "order",
            prompt: "Reconstruis la phrase",
            french: "Oui, merci.",
            words: ["Eɛ", ",", "awanou", "."],
            answer: ["Eɛ", ",", "awanou", "."],
          },
        ],
      },
      {
        id: "w1l3",
        title: "Comment vas-tu ?",
        emoji: "🤝",
        exercises: [
          {
            type: "choice",
            prompt: "Compréhension",
            question: "« A fɔn ganji à ? » signifie...",
            options: [
              "As-tu mangé ?",
              "Comment vas-tu ?",
              "Où vas-tu ?",
              "Qui es-tu ?",
            ],
            answer: "Comment vas-tu ?",
          },
          {
            type: "translate",
            prompt: "Traduire en Fon",
            from: "Je vais bien",
            to: "fon",
            answer: "Un fɔn ganji",
            choices: ["Un fɔn ganji", "A fɔn ganji", "Mawu kú", "Awanou nɛ"],
          },
          {
            type: "match",
            prompt: "Associe",
            pairs: [
              { fr: "Comment vas-tu ?", fon: "A fɔn ganji à ?" },
              { fr: "Je vais bien", fon: "Un fɔn ganji" },
              { fr: "Et toi ?", fon: "Bɔ hwɛ ɔ ?" },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "w2",
    title: "Famille",
    subtitle: "Le cœur du foyer",
    emoji: "👨‍👩‍👧",
    color: "gold",
    lessons: [
      {
        id: "w2l1",
        title: "Père & Mère",
        emoji: "❤️",
        exercises: [
          {
            type: "choice",
            prompt: "Nouveau mot",
            question: "Comment dit-on « Père » en Fon ?",
            options: ["Nɔ", "Tɔ", "Vĭ", "Nɔví"],
            answer: "Tɔ",
          },
          {
            type: "choice",
            prompt: "Nouveau mot",
            question: "Comment dit-on « Mère » en Fon ?",
            options: ["Tɔ", "Nɔ", "Vĭ", "Daa"],
            answer: "Nɔ",
          },
          {
            type: "translate",
            prompt: "Traduire en Fon",
            from: "Ma mère",
            to: "fon",
            answer: "Nɔ ce",
            choices: ["Nɔ ce", "Tɔ ce", "Vĭ ce", "Nɔví ce"],
          },
          {
            type: "order",
            prompt: "Reconstruis",
            french: "Mon père va bien.",
            words: ["Tɔ", "ce", "fɔn", "ganji", "."],
            answer: ["Tɔ", "ce", "fɔn", "ganji", "."],
          },
        ],
      },
      {
        id: "w2l2",
        title: "Frère, Sœur, Enfant",
        emoji: "👶",
        exercises: [
          {
            type: "choice",
            prompt: "Nouveau mot",
            question: "« Vĭ » signifie...",
            options: ["Frère", "Mère", "Enfant", "Ami"],
            answer: "Enfant",
          },
          {
            type: "choice",
            prompt: "Nouveau mot",
            question: "Comment dit-on « Frère/Sœur » (sibling) en Fon ?",
            options: ["Nɔví", "Tɔ", "Vĭ", "Daa"],
            answer: "Nɔví",
            hint: "« Nɔví » désigne frère ou sœur indifféremment.",
          },
          {
            type: "match",
            prompt: "Associe",
            pairs: [
              { fr: "Père", fon: "Tɔ" },
              { fr: "Mère", fon: "Nɔ" },
              { fr: "Enfant", fon: "Vĭ" },
              { fr: "Frère/Sœur", fon: "Nɔví" },
            ],
          },
          {
            type: "translate",
            prompt: "Traduire en français",
            from: "Nɔví ce",
            to: "fr",
            answer: "Mon frère",
            choices: ["Mon frère", "Ma mère", "Mon enfant", "Mon père"],
          },
          {
            type: "order",
            prompt: "Reconstruis",
            french: "Mon enfant va bien.",
            words: ["Vĭ", "ce", "fɔn", "ganji", "."],
            answer: ["Vĭ", "ce", "fɔn", "ganji", "."],
          },
        ],
      },
    ],
  },
  {
    id: "w3",
    title: "Pronoms personnels",
    subtitle: "A, É, Mǐ, Mi, Nyɛ, Hwɛ…",
    emoji: "🗣️",
    color: "coral",
    lessons: [
      {
        id: "w3l1",
        title: "Singulier sujet : A & É",
        emoji: "👤",
        exercises: [
          {
            type: "choice",
            prompt: "Pronom sujet",
            question: "« A » correspond à quel pronom français ?",
            options: ["Je", "Tu", "Il / Elle", "Nous"],
            answer: "Tu",
            hint: "A se place devant le verbe : « A sè à ? » = As-tu entendu ?",
          },
          {
            type: "choice",
            prompt: "Pronom sujet",
            question: "« É » correspond à...",
            options: ["Je", "Tu", "Il / Elle / Cela", "Vous"],
            answer: "Il / Elle / Cela",
            hint: "É devient ‘é’ après l'élision d'une voyelle ouverte.",
          },
          {
            type: "translate",
            prompt: "Traduire en français",
            from: "A sè gànjí",
            to: "fr",
            answer: "Tu as bien entendu",
            choices: [
              "Tu as bien entendu",
              "Je vais bien",
              "Il a entendu",
              "Nous avons compris",
            ],
          },
          {
            type: "translate",
            prompt: "Traduire en français",
            from: "É tíìn",
            to: "fr",
            answer: "Il existe",
            choices: ["Il existe", "Il est parti", "Tu es là", "Je suis là"],
          },
          {
            type: "match",
            prompt: "Associe pronom et sens",
            pairs: [
              { fr: "Tu (sujet)", fon: "A" },
              { fr: "Il / Elle (sujet)", fon: "É" },
              { fr: "Le, la, l' (complément)", fon: "è" },
              { fr: "Lui (complément)", fon: "È / i" },
            ],
          },
          {
            type: "order",
            prompt: "Reconstruis",
            french: "As-tu entendu ?",
            words: ["A", "sè", "à", "?"],
            answer: ["A", "sè", "à", "?"],
          },
        ],
      },
      {
        id: "w3l2",
        title: "Formes emphatiques : Nyɛ, Hwɛ, Éyé",
        emoji: "💪",
        exercises: [
          {
            type: "choice",
            prompt: "Forme absolue",
            question: "« Nyɛ » signifie...",
            options: ["Moi, je", "Toi", "Lui", "Nous"],
            answer: "Moi, je",
          },
          {
            type: "choice",
            prompt: "Forme absolue",
            question: "« Hwɛ » signifie...",
            options: ["Moi", "Toi", "Lui", "Vous"],
            answer: "Toi",
            hint: "Forme emphatique : « Hwɛ ɔ́, a nɔ kò àfyɔ̀n dín » = Toi, tu ricanes trop.",
          },
          {
            type: "choice",
            prompt: "Forme emphatique",
            question: "« Éyé » désigne...",
            options: ["Moi-même", "Toi-même", "Il / Elle / Lui (emphatique)", "Eux"],
            answer: "Il / Elle / Lui (emphatique)",
          },
          {
            type: "translate",
            prompt: "Traduire en français",
            from: "Nyɛ kpódó hwi kpán",
            to: "fr",
            answer: "Moi et toi",
            choices: ["Moi et toi", "Toi et lui", "Nous deux frères", "Moi seul"],
          },
          {
            type: "match",
            prompt: "Associe",
            pairs: [
              { fr: "Moi, je", fon: "Nyɛ" },
              { fr: "Toi", fon: "Hwɛ" },
              { fr: "Lui (emphatique)", fon: "Éyé" },
              { fr: "Toi-même (réflexif)", fon: "Hwiɖéé" },
            ],
          },
          {
            type: "order",
            prompt: "Reconstruis",
            french: "Toi, tu ricanes trop.",
            words: ["Hwɛ", "ɔ́", ",", "a", "nɔ", "kò", "àfyɔ̀n", "dín"],
            answer: ["Hwɛ", "ɔ́", ",", "a", "nɔ", "kò", "àfyɔ̀n", "dín"],
          },
        ],
      },
      {
        id: "w3l3",
        title: "Pluriel : Mǐ (nous) & Mi (vous)",
        emoji: "👥",
        exercises: [
          {
            type: "choice",
            prompt: "Pluriel",
            question: "« Mǐ » signifie...",
            options: ["Je", "Tu", "Nous", "Vous"],
            answer: "Nous",
            hint: "Mǐ = 1ʳᵉ personne du pluriel (sujet ou complément).",
          },
          {
            type: "choice",
            prompt: "Pluriel",
            question: "« Mi » signifie...",
            options: ["Je", "Tu", "Nous", "Vous"],
            answer: "Vous",
          },
          {
            type: "translate",
            prompt: "Traduire en français",
            from: "Mǐ wá",
            to: "fr",
            answer: "Nous sommes venus",
            choices: [
              "Nous sommes venus",
              "Vous êtes venus",
              "Ils sont venus",
              "Je suis venu",
            ],
          },
          {
            type: "translate",
            prompt: "Traduire en français",
            from: "Mi wá",
            to: "fr",
            answer: "Venez",
            choices: ["Venez", "Nous venons", "Ils viennent", "Tu viens"],
          },
          {
            type: "match",
            prompt: "Associe",
            pairs: [
              { fr: "Nous", fon: "Mǐ" },
              { fr: "Vous", fon: "Mi" },
              { fr: "Nous-mêmes", fon: "Mǐ ɖésú" },
              { fr: "Notre père commun", fon: "Mǐtɔ́" },
            ],
          },
          {
            type: "order",
            prompt: "Reconstruis",
            french: "À demain.",
            words: ["Sɔ̀", "mǐ", "nà", "kpé"],
            answer: ["Sɔ̀", "mǐ", "nà", "kpé"],
          },
        ],
      },
      {
        id: "w3l4",
        title: "Ma : subjonctif & impératif",
        emoji: "✨",
        exercises: [
          {
            type: "choice",
            prompt: "Pronom spécial",
            question: "« Ma » s'emploie pour...",
            options: [
              "Le passé simple",
              "Le subjonctif & l'impératif (1ʳᵉ pers.)",
              "La négation",
              "La 3ᵉ personne",
            ],
            answer: "Le subjonctif & l'impératif (1ʳᵉ pers.)",
            hint: "Ex : « Má ɖɔ́ nú mi » = Je vous le dis (que je vous dise).",
          },
          {
            type: "translate",
            prompt: "Traduire en français",
            from: "Má kpɔ́n",
            to: "fr",
            answer: "Que je voie",
            choices: ["Que je voie", "Je regarde", "Regarde-moi", "Il regarde"],
          },
          {
            type: "translate",
            prompt: "Traduire en français",
            from: "Mì nú má yì",
            to: "fr",
            answer: "Allons, partons",
            choices: [
              "Allons, partons",
              "Je m'en vais",
              "Reste avec nous",
              "Viens vite",
            ],
          },
          {
            type: "match",
            prompt: "Associe phrase & sens",
            pairs: [
              { fr: "Puis-je venir ?", fon: "Má wá à ?" },
              { fr: "Au revoir", fon: "Ma yi bo wa" },
              { fr: "Donne-moi à boire", fon: "Ná mí sìn má nù" },
              { fr: "Passe devant", fon: "Zɔn ma yì" },
            ],
          },
          {
            type: "order",
            prompt: "Reconstruis",
            french: "Je vous le dis.",
            words: ["Má", "ɖɔ́", "nú", "mi"],
            answer: ["Má", "ɖɔ́", "nú", "mi"],
          },
        ],
      },
      {
        id: "w3l5",
        title: "Nyɛ, Nyì, Un (1ʳᵉ pers.)",
        emoji: "🙋",
        exercises: [
          {
            type: "choice",
            prompt: "Pronom 1ʳᵉ pers.",
            question: "« Un » correspond à...",
            options: ["Je (sujet)", "Moi (complément)", "Tu", "Il"],
            answer: "Je (sujet)",
            hint: "Un se place devant le verbe : « Un jáwè » = J'arrive.",
          },
          {
            type: "choice",
            prompt: "Forme emphatique",
            question: "« Nyɛ » signifie...",
            options: ["Je (sujet neutre)", "Moi (emphatique/complément)", "Toi", "Lui"],
            answer: "Moi (emphatique/complément)",
            hint: "Nyì est une variante de Nyɛ.",
          },
          {
            type: "translate",
            prompt: "Traduire en français",
            from: "Un ná yì Glèxwé",
            to: "fr",
            answer: "J'irai à Ouidah",
            choices: ["J'irai à Ouidah", "Je viens de Ouidah", "Tu vas à Ouidah", "Il est à Ouidah"],
          },
          {
            type: "translate",
            prompt: "Traduire en français",
            from: "Nyɛ ma sanfú né",
            to: "fr",
            answer: "Je m'en fous",
            choices: ["Je m'en fous", "Je suis fatigué", "J'ai faim", "Je viens"],
          },
          {
            type: "order",
            prompt: "Reconstruis",
            french: "J'arrive.",
            words: ["Un", "jáwè"],
            answer: ["Un", "jáwè"],
          },
          {
            type: "match",
            prompt: "Associe",
            pairs: [
              { fr: "Je (sujet)", fon: "Un" },
              { fr: "Moi (emphatique)", fon: "Nyɛ" },
              { fr: "Moi-même", fon: "Nyɛɖéé" },
              { fr: "Mon frère aîné", fon: "Nyɛ kpódó fofó" },
            ],
          },
        ],
      },
      {
        id: "w3l6",
        title: "Wè (toi) & Yě (ils/elles)",
        emoji: "👥",
        exercises: [
          {
            type: "choice",
            prompt: "Pronom complément",
            question: "« Wè » signifie...",
            options: ["Toi (complément)", "Vous", "Lui", "Nous"],
            answer: "Toi (complément)",
            hint: "Wè suit le verbe : « Doo nú wè » = Bienvenue à toi.",
          },
          {
            type: "choice",
            prompt: "Pluriel",
            question: "« Yě » signifie...",
            options: ["Nous", "Vous", "Ils / Elles", "Eux-mêmes"],
            answer: "Ils / Elles",
          },
          {
            type: "translate",
            prompt: "Traduire en français",
            from: "Agoò nú wè",
            to: "fr",
            answer: "Prends garde à toi",
            choices: ["Prends garde à toi", "Bienvenue à toi", "Merci à toi", "Honte à toi"],
          },
          {
            type: "translate",
            prompt: "Traduire en français",
            from: "Yè klán gbɛ̀",
            to: "fr",
            answer: "Ils ne s'entendent plus",
            choices: ["Ils ne s'entendent plus", "Ils sont arrivés", "Ils ont crié", "Ils chantent"],
          },
          {
            type: "order",
            prompt: "Reconstruis",
            french: "Bienvenue à toi.",
            words: ["Doo", "nú", "wè"],
            answer: ["Doo", "nú", "wè"],
          },
          {
            type: "match",
            prompt: "Associe",
            pairs: [
              { fr: "Toi (complément)", fon: "Wè" },
              { fr: "Ils / Elles", fon: "Yě" },
              { fr: "Eux-mêmes", fon: "Yěɖéé" },
              { fr: "Ils ont eu honte", fon: "Winnyá hú yě" },
            ],
          },
        ],
      },
      {
        id: "w3l7",
        title: "Possessifs & réflexifs",
        emoji: "🪞",
        exercises: [
          {
            type: "choice",
            prompt: "Possessif",
            question: "« Towe » signifie...",
            options: ["Mon", "Ton", "Son", "Notre"],
            answer: "Ton",
            hint: "Afɔ towe = ton pied ; Nù tówé = ta chose.",
          },
          {
            type: "choice",
            prompt: "Réflexif",
            question: "« Hwiɖéé » signifie...",
            options: ["Moi-même", "Toi-même", "Lui-même", "Vous-mêmes"],
            answer: "Toi-même",
          },
          {
            type: "translate",
            prompt: "Traduire en français",
            from: "Nù tówé hú dó mì",
            to: "fr",
            answer: "J'ai besoin de toi",
            choices: ["J'ai besoin de toi", "C'est à toi", "Je viens vers toi", "Tu me cherches"],
          },
          {
            type: "translate",
            prompt: "Traduire en Fon",
            from: "Notre, nos",
            to: "fon",
            answer: "Mǐtɔ̀n",
            choices: ["Mǐtɔ̀n", "Mitɔ̀n", "Yětɔ̀n", "Towe"],
          },
          {
            type: "match",
            prompt: "Associe possessifs & réflexifs",
            pairs: [
              { fr: "Notre, nos", fon: "Mǐtɔ̀n" },
              { fr: "Votre, vos", fon: "Mitɔ̀n" },
              { fr: "Leur, leurs", fon: "Yětɔ̀n" },
              { fr: "Vous-mêmes", fon: "Miɖéé" },
            ],
          },
          {
            type: "order",
            prompt: "Reconstruis",
            french: "C'est à toi.",
            words: ["Towe", "wè"],
            answer: ["Towe", "wè"],
          },
        ],
      },
    ],
  },
  {
    id: "w4",
    title: "Conjugaison",
    subtitle: "Impératif, temps & particules",
    emoji: "⚡",
    color: "primary",
    lessons: [
      {
        id: "w4l1",
        title: "Impératif singulier",
        emoji: "❗",
        exercises: [
          {
            type: "choice",
            prompt: "Règle",
            question: "Comment forme-t-on l'impératif (tu) en Fon ?",
            options: [
              "On ajoute « na » devant le verbe",
              "On utilise le radical du verbe seul",
              "On met « mi » devant",
              "On ajoute « ó » à la fin",
            ],
            answer: "On utilise le radical du verbe seul",
            hint: "Ex : Gbɔ̀ ! = Calme-toi !",
          },
          {
            type: "translate",
            prompt: "Traduire en français",
            from: "N'àbɔ̌ !",
            to: "fr",
            answer: "Tais-toi !",
            choices: ["Tais-toi !", "Calme-toi !", "Lève-toi !", "Viens !"],
          },
          {
            type: "translate",
            prompt: "Traduire en Fon",
            from: "Viens ici",
            to: "fon",
            answer: "Wǎ fí",
            choices: ["Wǎ fí", "Yì fí", "Sɛ yi", "Wǎ mì"],
          },
          {
            type: "order",
            prompt: "Reconstruis",
            french: "Recule un peu.",
            words: ["Sɛ", "yi", "ɖòn", "kpɛɖé"],
            answer: ["Sɛ", "yi", "ɖòn", "kpɛɖé"],
          },
          {
            type: "match",
            prompt: "Associe",
            pairs: [
              { fr: "Calme-toi !", fon: "Gbɔ̀ !" },
              { fr: "Tais-toi !", fon: "N'àbɔ̌ !" },
              { fr: "Viens vers moi", fon: "Wǎ mì" },
              { fr: "Attention !", fon: "Xwe sɔ̀ !" },
            ],
          },
        ],
      },
      {
        id: "w4l2",
        title: "Impératif pluriel (Mi…)",
        emoji: "👥",
        exercises: [
          {
            type: "choice",
            prompt: "Règle",
            question: "Pour donner un ordre à plusieurs personnes, on place...",
            options: ["« Na » devant le verbe", "« Mi » devant le verbe", "« Ko » devant", "Rien"],
            answer: "« Mi » devant le verbe",
            hint: "Mi glá ! = Soyez courageux !",
          },
          {
            type: "translate",
            prompt: "Traduire en français",
            from: "Mi dó gbɛ̀",
            to: "fr",
            answer: "Bonne nuit à vous",
            choices: ["Bonne nuit à vous", "Bonjour à vous", "Arrêtez le travail", "Mangez"],
          },
          {
            type: "translate",
            prompt: "Traduire en Fon",
            from: "Prenez et mangez.",
            to: "fon",
            answer: "Mi yí bó ɖù",
            choices: ["Mi yí bó ɖù", "Mi ná tèn", "Mi glá", "Mi sé yi"],
          },
          {
            type: "order",
            prompt: "Reconstruis",
            french: "Arrêtez le travail.",
            words: ["Mi", "ɖ'álɔ", "té"],
            answer: ["Mi", "ɖ'álɔ", "té"],
          },
          {
            type: "match",
            prompt: "Associe",
            pairs: [
              { fr: "Soyez courageux !", fon: "Mi glá !" },
              { fr: "Reculez-vous", fon: "Mi sé yi gǔɖò" },
              { fr: "Rangez-vous", fon: "Mi ná tèn" },
              { fr: "Écoutez ces paroles", fon: "Mi ɖó tó xó élɔ́ lɛ́" },
            ],
          },
        ],
      },
      {
        id: "w4l3",
        title: "Forme négative (Ma… ó)",
        emoji: "🚫",
        exercises: [
          {
            type: "choice",
            prompt: "Règle",
            question: "Comment exprime-t-on un ordre négatif en Fon ?",
            options: [
              "« Ma » devant le verbe + « ó » à la fin",
              "« Na » devant",
              "Inversion du verbe",
              "« Ko » devant",
            ],
            answer: "« Ma » devant le verbe + « ó » à la fin",
            hint: "Ma j'àyì ó = Ne tombe pas.",
          },
          {
            type: "translate",
            prompt: "Traduire en français",
            from: "Ma bà ɖò nà ó",
            to: "fr",
            answer: "Ne cherche pas à comprendre",
            choices: [
              "Ne cherche pas à comprendre",
              "Ne tombe pas",
              "Ne me touche pas",
              "Ne crie pas",
            ],
          },
          {
            type: "translate",
            prompt: "Traduire en Fon",
            from: "Ne me touche pas.",
            to: "fon",
            answer: "Ma ɖ'álɔ̀ wù yé ó",
            choices: [
              "Ma ɖ'álɔ̀ wù yé ó",
              "Ma j'àyì ó",
              "Ma bà ɖò nà ó",
              "Ma sɛ yi ó",
            ],
          },
          {
            type: "order",
            prompt: "Reconstruis",
            french: "Ne tombe pas.",
            words: ["Ma", "j'àyì", "ó"],
            answer: ["Ma", "j'àyì", "ó"],
          },
          {
            type: "match",
            prompt: "Associe",
            pairs: [
              { fr: "Ne tombe pas", fon: "Ma j'àyì ó" },
              { fr: "Ne cherche pas à comprendre", fon: "Ma bà ɖò nà ó" },
              { fr: "Ne restez pas dispersés", fon: "Mi ma nɔ gdadógbádó ó" },
              { fr: "Ne soyez pas inquiets", fon: "Nùɖé má gb'ayi dó nú mi ó" },
            ],
          },
        ],
      },
      {
        id: "w4l4",
        title: "Particules : bo, ló, ní, vě",
        emoji: "✨",
        exercises: [
          {
            type: "choice",
            prompt: "Particule",
            question: "La particule « bo » sert à...",
            options: [
              "Renforcer l'impératif (« donc »)",
              "Marquer la négation",
              "Marquer le futur",
              "Marquer le passé",
            ],
            answer: "Renforcer l'impératif (« donc »)",
            hint: "Wǎ bó ! = Viens donc !",
          },
          {
            type: "choice",
            prompt: "Particule",
            question: "« Ló » exprime...",
            options: ["Le souhait", "L'impatience", "Le passé", "Le futur"],
            answer: "Le souhait",
            hint: "Mǎwù ló bló ɖagbe = Que Dieu te fasse du bien.",
          },
          {
            type: "translate",
            prompt: "Traduire en français",
            from: "Sin ní yi kɔ̀",
            to: "fr",
            answer: "À votre santé !",
            choices: ["À votre santé !", "Bonne nuit", "Bon voyage", "Bienvenue"],
          },
          {
            type: "translate",
            prompt: "Traduire en français",
            from: "Vè glá",
            to: "fr",
            answer: "Sois courageux",
            choices: ["Sois courageux", "Calme-toi", "Tais-toi", "Avance"],
          },
          {
            type: "match",
            prompt: "Associe particule & sens",
            pairs: [
              { fr: "bo : renforce l'ordre", fon: "Wǎ bó !" },
              { fr: "ló : souhait", fon: "Mǎwù ló bló ɖagbe" },
              { fr: "ní : souhait/ordre", fon: "Sin ní yi kɔ̀" },
              { fr: "vě : exhortation", fon: "Vè kpɔ́n" },
            ],
          },
        ],
      },
      {
        id: "w4l5",
        title: "Aoriste (radical seul)",
        emoji: "📜",
        exercises: [
          {
            type: "choice",
            prompt: "Règle",
            question: "L'aoriste (action accomplie) s'exprime...",
            options: [
              "Par le radical du verbe seul",
              "Avec la particule « na »",
              "Avec « ko »",
              "Avec « nɔ »",
            ],
            answer: "Par le radical du verbe seul",
            hint: "É jǎwè = Il arrive. Un wá = Je suis venu.",
          },
          {
            type: "translate",
            prompt: "Traduire en français",
            from: "A sè à ?",
            to: "fr",
            answer: "As-tu entendu ?",
            choices: ["As-tu entendu ?", "As-tu vu ?", "Es-tu venu ?", "As-tu mangé ?"],
          },
          {
            type: "translate",
            prompt: "Traduire en français",
            from: "Un wá yì Zanjɛ́nnádó",
            to: "fr",
            answer: "J'arrive de Zagnanado",
            choices: [
              "J'arrive de Zagnanado",
              "Je vais à Zagnanado",
              "Il vient de Zagnanado",
              "Nous partons à Zagnanado",
            ],
          },
          {
            type: "order",
            prompt: "Reconstruis",
            french: "Il arrive.",
            words: ["É", "jǎwè"],
            answer: ["É", "jǎwè"],
          },
          {
            type: "match",
            prompt: "Associe",
            pairs: [
              { fr: "As-tu entendu ?", fon: "A sè à ?" },
              { fr: "Il arrive", fon: "É jǎwè" },
              { fr: "C'est très bon", fon: "É víví káká" },
              { fr: "D'où viens-tu ?", fon: "Fité à wǎ ?" },
            ],
          },
        ],
      },
      {
        id: "w4l6",
        title: "Passé accompli (ko)",
        emoji: "⏪",
        exercises: [
          {
            type: "choice",
            prompt: "Règle",
            question: "La particule « ko » placée entre sujet et verbe indique...",
            options: [
              "Une action totalement terminée (déjà)",
              "Le futur",
              "Le présent habituel",
              "Une négation",
            ],
            answer: "Une action totalement terminée (déjà)",
            hint: "Un ko kpò = Je suis déjà vieux.",
          },
          {
            type: "translate",
            prompt: "Traduire en français",
            from: "Mǐ kó wá Gbɔxíkɔ̀n",
            to: "fr",
            answer: "Nous sommes arrivés à Bohicon",
            choices: [
              "Nous sommes arrivés à Bohicon",
              "Nous irons à Bohicon",
              "Nous venons de Bohicon",
              "Ils sont à Bohicon",
            ],
          },
          {
            type: "translate",
            prompt: "Traduire en Fon",
            from: "J'ai déjà vendu à quelqu'un.",
            to: "fon",
            answer: "Un ko kpan'lɔ̀",
            choices: ["Un ko kpan'lɔ̀", "Un ná kpan'lɔ̀", "Un nɔ kpan'lɔ̀", "Un kpan'lɔ̀"],
          },
          {
            type: "order",
            prompt: "Reconstruis",
            french: "Je suis déjà vieux.",
            words: ["Un", "ko", "kpò"],
            answer: ["Un", "ko", "kpò"],
          },
          {
            type: "match",
            prompt: "Associe",
            pairs: [
              { fr: "Je suis déjà vieux", fon: "Un ko kpò" },
              { fr: "Nous sommes arrivés à Bohicon", fon: "Mǐ kó wá Gbɔxíkɔ̀n" },
              { fr: "Oui, je te rattrape déjà", fon: "Un ko jàwè mɛ́ !" },
              { fr: "Nous aurions déjà dîné", fon: "Mǐ nà kó ɖu nǔ" },
            ],
          },
        ],
      },
      {
        id: "w4l7",
        title: "Futur (na)",
        emoji: "🚀",
        exercises: [
          {
            type: "choice",
            prompt: "Règle",
            question: "Pour exprimer le futur, on place...",
            options: [
              "« na » entre le sujet et le verbe",
              "« ko » devant le verbe",
              "« nɔ » devant le verbe",
              "« ɖò…wɛ̀ » autour du verbe",
            ],
            answer: "« na » entre le sujet et le verbe",
            hint: "Un ná yì Glèxwé = J'irai à Ouidah.",
          },
          {
            type: "translate",
            prompt: "Traduire en français",
            from: "É ná fɛ́ gba ta wè",
            to: "fr",
            answer: "Cela retombera sur toi",
            choices: [
              "Cela retombera sur toi",
              "Il viendra te voir",
              "Tu seras heureux",
              "Cela te plaira",
            ],
          },
          {
            type: "translate",
            prompt: "Traduire en Fon",
            from: "J'irai à Ouidah.",
            to: "fon",
            answer: "Un ná yì Glèxwé",
            choices: ["Un ná yì Glèxwé", "Un ko yì Glèxwé", "Un yì Glèxwé", "Un nɔ yì Glèxwé"],
          },
          {
            type: "order",
            prompt: "Reconstruis",
            french: "Ses fruits seront bons.",
            words: ["Sísɛ́n", "tɔ́n", "ná", "nylá", "mɔ̌"],
            answer: ["Sísɛ́n", "tɔ́n", "ná", "nylá", "mɔ̌"],
          },
          {
            type: "match",
            prompt: "Associe",
            pairs: [
              { fr: "J'irai à Ouidah", fon: "Un ná yì Glèxwé" },
              { fr: "Il a dit qu'il viendra", fon: "É ɖɔ̀ émí ná wá" },
              { fr: "Je voudrais être ton ami", fon: "Un jlo ná zùn xɔ́ntɔ́n xá wè" },
              { fr: "Venez vite que nous partions", fon: "Mi yá wǔ a caca nú mì ná yì" },
            ],
          },
        ],
      },
      {
        id: "w4l8",
        title: "Habituel (nɔ)",
        emoji: "🔁",
        exercises: [
          {
            type: "choice",
            prompt: "Règle",
            question: "La particule « nɔ » entre sujet et verbe exprime...",
            options: [
              "Une habitude / un état durable",
              "Le futur",
              "Une action terminée",
              "La négation",
            ],
            answer: "Une habitude / un état durable",
            hint: "É nɔ ɖɔ fɔngbe ganjí = Il parle bien le fon.",
          },
          {
            type: "translate",
            prompt: "Traduire en français",
            from: "Cukú nɔ lun ɖè",
            to: "fr",
            answer: "Le chien bave",
            choices: ["Le chien bave", "Le chien aboie", "Le chien dort", "Le chien court"],
          },
          {
            type: "translate",
            prompt: "Traduire en Fon",
            from: "Ce chien aboie beaucoup.",
            to: "fon",
            answer: "Avún élɔ́ nɔ hó ɖésú",
            choices: [
              "Avún élɔ́ nɔ hó ɖésú",
              "Avún élɔ́ ɖò hó wɛ̀",
              "Avún élɔ́ ná hó",
              "Avún élɔ́ ko hó",
            ],
          },
          {
            type: "order",
            prompt: "Reconstruis",
            french: "Il parle bien le fon.",
            words: ["É", "nɔ", "ɖɔ", "fɔngbe", "ganjí"],
            answer: ["É", "nɔ", "ɖɔ", "fɔngbe", "ganjí"],
          },
          {
            type: "match",
            prompt: "Associe",
            pairs: [
              { fr: "Il parle bien le fon", fon: "É nɔ ɖɔ fɔngbe ganjí" },
              { fr: "Le chien bave", fon: "Cukú nɔ lun ɖè" },
              { fr: "Il est infatigable", fon: "Nù nɔ ci kɔn'í ǎ" },
              { fr: "L'eau de ruissellement coule", fon: "Ayìsún nɔ sà" },
            ],
          },
        ],
      },
      {
        id: "w4l9",
        title: "Progressif (ɖò… wɛ̀)",
        emoji: "🌀",
        exercises: [
          {
            type: "choice",
            prompt: "Règle",
            question: "« ɖò … wɛ̀ » autour du verbe exprime...",
            options: [
              "Une action en cours (être en train de)",
              "Une habitude",
              "Le passé",
              "Le futur",
            ],
            answer: "Une action en cours (être en train de)",
            hint: "É ɖò bìbí wɛ̀ = Il est en train de cuire.",
          },
          {
            type: "choice",
            prompt: "Piège",
            question: "Différence entre « nɔ » et « ɖò…wɛ̀ » ?",
            options: [
              "« nɔ » = habitude/état ; « ɖò…wɛ̀ » = action en cours",
              "Ils signifient la même chose",
              "« nɔ » = futur ; « ɖò…wɛ̀ » = passé",
              "« ɖò…wɛ̀ » sert à nier",
            ],
            answer: "« nɔ » = habitude/état ; « ɖò…wɛ̀ » = action en cours",
          },
          {
            type: "translate",
            prompt: "Traduire en français",
            from: "Tɔ̀ ɔ́ ɖò sin ɖi wɛ̀",
            to: "fr",
            answer: "Le fleuve est en crue",
            choices: [
              "Le fleuve est en crue",
              "Le fleuve coule lentement",
              "Le fleuve s'est tari",
              "Le fleuve déborde toujours",
            ],
          },
          {
            type: "translate",
            prompt: "Traduire en Fon",
            from: "Le coq chante.",
            to: "fon",
            answer: "Koklójó ɖò asi kó wɛ̀",
            choices: [
              "Koklójó ɖò asi kó wɛ̀",
              "Koklójó nɔ asi kó",
              "Koklójó ná asi kó",
              "Koklójó ko asi kó",
            ],
          },
          {
            type: "order",
            prompt: "Reconstruis",
            french: "Il est en train de cuire.",
            words: ["É", "ɖò", "bìbí", "wɛ̀"],
            answer: ["É", "ɖò", "bìbí", "wɛ̀"],
          },
          {
            type: "match",
            prompt: "Associe",
            pairs: [
              { fr: "La pluie se fait plus forte", fon: "Jǐ ɖò wuwu wɛ̀" },
              { fr: "La maladie s'aggrave", fon: "Azɔ̀n ɔ ɖò syɛ́nsyɛ́n wɛ̀" },
              { fr: "Ils se hâtent", fon: "Yě ɖò fyáfyá wɛ̀" },
              { fr: "La nuit vient", fon: "Zǎn ɖò kúkú wɛ̀" },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "w5",
    title: "Verbes essentiels",
    subtitle: "Racines verbales du Fɔngbè",
    emoji: "🌿",
    color: "primary",
    lessons: [
      {
        id: "w5l1",
        title: "Verbes du quotidien",
        emoji: "🍲",
        exercises: [
          {
            type: "choice",
            prompt: "Nouveau verbe",
            question: "Comment dit-on « manger » en Fon ?",
            options: ["dù", "nù", "wà", "kú"],
            answer: "dù",
            hint: "Dù signifie aussi « consommer ».",
          },
          {
            type: "choice",
            prompt: "Vocabulaire",
            question: "« nù » veut dire...",
            options: ["dormir", "boire", "voir", "marcher"],
            answer: "boire",
          },
          {
            type: "translate",
            prompt: "Traduire en Fon",
            from: "voir",
            to: "fon",
            answer: "mɔ̀",
            choices: ["mɔ̀", "sè", "kpɔ́n", "byɔ̌"],
          },
          {
            type: "match",
            prompt: "Associe verbe et sens",
            pairs: [
              { fr: "dormir", fon: "dɔ̆" },
              { fr: "marcher", fon: "zɔ̀n" },
              { fr: "entendre", fon: "sé" },
              { fr: "parler / dire", fon: "ɖɔ̀" },
            ],
          },
          {
            type: "choice",
            prompt: "Choisis",
            question: "« faire » se dit...",
            options: ["wà", "wǎ", "và", "fá"],
            answer: "wà",
          },
          {
            type: "translate",
            prompt: "Traduire en Fon",
            from: "venir",
            to: "fon",
            answer: "wǎ",
            choices: ["wǎ", "wà", "yì", "tɔ́n"],
          },
        ],
      },
      {
        id: "w5l2",
        title: "Action & mouvement",
        emoji: "🏃",
        exercises: [
          {
            type: "match",
            prompt: "Associe",
            pairs: [
              { fr: "arriver", fon: "wǎ" },
              { fr: "sortir", fon: "tɔ́n" },
              { fr: "aller", fon: "yì" },
              { fr: "tomber", fon: "jɛ̀" },
            ],
          },
          {
            type: "choice",
            prompt: "Verbe",
            question: "Comment dit-on « ouvrir » ?",
            options: ["hùn", "sú", "tɔ́n", "blǎ"],
            answer: "hùn",
          },
          {
            type: "choice",
            prompt: "Verbe",
            question: "« sú » signifie...",
            options: ["ouvrir", "fermer", "courir", "lever"],
            answer: "fermer",
            hint: "Sú : fermer / barrer.",
          },
          {
            type: "translate",
            prompt: "Traduire en Fon",
            from: "attacher",
            to: "fon",
            answer: "blǎ",
            choices: ["blǎ", "ɖè", "sá", "kàn"],
          },
          {
            type: "match",
            prompt: "Associe",
            pairs: [
              { fr: "casser", fon: "wɛ̌n" },
              { fr: "lever", fon: "zě" },
              { fr: "pousser", fon: "wǔ" },
              { fr: "frapper", fon: "xò" },
            ],
          },
          {
            type: "order",
            prompt: "Reconstruis",
            french: "Il sort.",
            words: ["É", "tɔ́n"],
            answer: ["É", "tɔ́n"],
          },
        ],
      },
      {
        id: "w5l3",
        title: "Verbes utiles",
        emoji: "🧠",
        exercises: [
          {
            type: "match",
            prompt: "Associe",
            pairs: [
              { fr: "apprendre", fon: "kplɔ́n" },
              { fr: "demander", fon: "byɔ̌" },
              { fr: "savoir / connaître", fon: "nyɔ̌" },
              { fr: "vouloir", fon: "jlǒ" },
            ],
          },
          {
            type: "choice",
            prompt: "Verbe",
            question: "« lìn » veut dire...",
            options: ["dormir", "penser", "venir", "voir"],
            answer: "penser",
          },
          {
            type: "translate",
            prompt: "Traduire en Fon",
            from: "donner",
            to: "fon",
            answer: "ná",
            choices: ["ná", "yí", "kó", "wà"],
          },
          {
            type: "choice",
            prompt: "Verbe",
            question: "« yí » signifie...",
            options: ["recevoir", "donner", "perdre", "garder"],
            answer: "recevoir",
          },
          {
            type: "match",
            prompt: "Associe",
            pairs: [
              { fr: "garder", fon: "có" },
              { fr: "oublier", fon: "wɔ̀n" },
              { fr: "chercher", fon: "bà" },
              { fr: "trouver / voir", fon: "mɔ̀" },
            ],
          },
          {
            type: "translate",
            prompt: "Traduire en Fon",
            from: "rire",
            to: "fon",
            answer: "kò",
            choices: ["kò", "kó", "kú", "kɔ̀"],
          },
        ],
      },
      {
        id: "w5l4",
        title: "Verbes composés (racine + nom)",
        emoji: "🧩",
        exercises: [
          {
            type: "choice",
            prompt: "Forme composée",
            question: "« Chanter » se dit littéralement…",
            options: ["jì hàn (émettre un chant)", "ɖɔ̀ hàn (dire chant)", "xò hàn (frapper chant)", "yí hàn (recevoir chant)"],
            answer: "jì hàn (émettre un chant)",
          },
          {
            type: "match",
            prompt: "Associe",
            pairs: [
              { fr: "accoucher", fon: "jì vǐ" },
              { fr: "acheter", fon: "xɔ̀ nǔ" },
              { fr: "balayer", fon: "zà ayǐ" },
              { fr: "battre le tambour", fon: "xò hǔn" },
            ],
          },
          {
            type: "match",
            prompt: "Associe",
            pairs: [
              { fr: "appeler quelqu'un", fon: "ylɔ̌ mɛ" },
              { fr: "tuer (assassiner)", fon: "hù mɛ" },
              { fr: "annoncer", fon: "ɖɔ̆ wɛ̀n" },
              { fr: "admirer", fon: "kpà mɛ" },
            ],
          },
          {
            type: "translate",
            prompt: "Traduire en Fon",
            from: "Brûler (consumer + feu)",
            to: "fon",
            answer: "jì myɔ̀",
            choices: ["jì myɔ̀", "jì hàn", "xò hǔn", "fɔ̀ xwé"],
          },
          {
            type: "choice",
            prompt: "Composé",
            question: "« Cambrioler » = ramasser maison =",
            options: ["fɔ̀ xwé", "gbà xwé", "xɔ̀ xwé", "blǎ xwé"],
            answer: "fɔ̀ xwé",
          },
          {
            type: "match",
            prompt: "Associe",
            pairs: [
              { fr: "coiffer", fon: "ɖò ɖà" },
              { fr: "chausser", fon: "ɖò afɔkpà" },
              { fr: "chasser", fon: "nyà gbě" },
              { fr: "boxer", fon: "nyì akodokwín" },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "w6",
    title: "Phrases courantes",
    subtitle: "Formes ɖò…wɛ̀, wɛ̀…ɖɛ̀ et impératif",
    emoji: "💬",
    color: "gold",
    lessons: [
      {
        id: "w6l1",
        title: "Le présent progressif ɖò…wɛ̀",
        emoji: "⏳",
        exercises: [
          {
            type: "choice",
            prompt: "Grammaire",
            question: "La forme « ɖò … wɛ̀ » sert à exprimer…",
            options: ["le passé", "une action en cours", "l'impératif", "la négation"],
            answer: "une action en cours",
            hint: "Équivalent du « être en train de … » français.",
          },
          {
            type: "translate",
            prompt: "Traduire en Fon",
            from: "J'ai le hoquet.",
            to: "fon",
            answer: "Un ɖò adɔ sɔ́ wɛ̀",
            choices: [
              "Un ɖò adɔ sɔ́ wɛ̀",
              "Un na adɔ sɔ́",
              "Un kpɔ́n adɔ sɔ́",
              "Un ɖò adɔ wɛ̀ sɔ́",
            ],
          },
          {
            type: "order",
            prompt: "Reconstruis",
            french: "Je tremble de froid.",
            words: ["Un", "ɖò", "avivɔ", "sísɔ́", "wɛ̀"],
            answer: ["Un", "ɖò", "avivɔ", "sísɔ́", "wɛ̀"],
          },
          {
            type: "match",
            prompt: "Associe (ɖò…wɛ̀)",
            pairs: [
              { fr: "Ils jouent au ballon.", fon: "Yě ɖò bɔ̆lu xo wɛ̀" },
              { fr: "Ils discutent.", fon: "Yě ɖò nǔ ɖɔ́n wɛ̀" },
              { fr: "Ils se disputent.", fon: "Yě ɖò jlɛ ɖo wɛ̀" },
              { fr: "Les enfants s'amusent.", fon: "Yɔkpɔ́vú lɛ́ ɖò ayihun da wɛ̀" },
            ],
          },
          {
            type: "translate",
            prompt: "Traduire en Fon",
            from: "Elle se maquille.",
            to: "fon",
            answer: "É ɖo nǔ sá dó nukún mɛ́ wɛ̀",
            choices: [
              "É ɖo nǔ sá dó nukún mɛ́ wɛ̀",
              "É sá nukún mɛ́",
              "É ɖò nukún wɛ̀",
              "É ɖò nǔ sá wɛ̀ mɛ́",
            ],
          },
          {
            type: "order",
            prompt: "Reconstruis",
            french: "Il me fait peur.",
            words: ["É", "ɖo", "xɛsi", "dó", "nú", "mí", "wɛ̀"],
            answer: ["É", "ɖo", "xɛsi", "dó", "nú", "mí", "wɛ̀"],
          },
        ],
      },
      {
        id: "w6l2",
        title: "L'interrogation wɛ̀ … ɖɛ̀",
        emoji: "❓",
        exercises: [
          {
            type: "choice",
            prompt: "Grammaire",
            question: "La forme « wɛ̀ … ɖɛ̀ » est la forme inversée de…",
            options: ["ná … wà", "ɖò … wɛ̀", "kɔ́ … mɛ̀", "ká … à"],
            answer: "ɖò … wɛ̀",
            hint: "Elle sert à interroger ou mettre en relief.",
          },
          {
            type: "translate",
            prompt: "Traduire en Fon",
            from: "Que cherches-tu ?",
            to: "fon",
            answer: "Ani ba w'a ɖɛ̀ ?",
            choices: ["Ani ba w'a ɖɛ̀ ?", "Ani a ba ?", "Mɛ a ba ɖɛ̀ ?", "Ani ɖò ba wɛ̀ ?"],
          },
          {
            type: "match",
            prompt: "Associe",
            pairs: [
              { fr: "Je viens du marché.", fon: "Aximɛ go sín wɛ un ɖɛ̀" },
              { fr: "Je cherche mon livre.", fon: "Wɛ̀má cé ba wɛ un ɖɛ̀" },
              { fr: "Je me promène seulement.", fon: "Sa ɖi wɛ un ɖɛ̀ kpowùn" },
              { fr: "C'est lui que j'attends.", fon: "É kpɔn wɛ un ɖɛ̀" },
            ],
          },
          {
            type: "order",
            prompt: "Reconstruis",
            french: "D'où viens-tu ?",
            words: ["Fitɛ́", "gó", "sín", "wɛ", "a", "ɖɛ̀", "?"],
            answer: ["Fitɛ́", "gó", "sín", "wɛ", "a", "ɖɛ̀", "?"],
          },
          {
            type: "translate",
            prompt: "Traduire en Fon",
            from: "Il regarde.",
            to: "fon",
            answer: "Kpínkpɔ́n wɛ́ é ɖɛ̀",
            choices: ["Kpínkpɔ́n wɛ́ é ɖɛ̀", "É kpɔ́n", "É ɖò kpɔ́n wɛ̀", "Kpɔ́n é ɖɛ̀"],
          },
          {
            type: "choice",
            prompt: "Sens",
            question: "« Mɛ nàhún ba wɛ a ɖɛ̀ ? » signifie…",
            options: [
              "Qui cherches-tu précisément ?",
              "Où vas-tu ?",
              "Que dis-tu ?",
              "Pourquoi pleures-tu ?",
            ],
            answer: "Qui cherches-tu précisément ?",
          },
        ],
      },
      {
        id: "w6l3",
        title: "Impératif & ordres",
        emoji: "✋",
        exercises: [
          {
            type: "choice",
            prompt: "Impératif",
            question: "« Regarde-moi » se dit…",
            options: ["Kpɔ́n mì", "Kpɔ́n è", "Un kpɔ́n", "Mì kpɔ́n"],
            answer: "Kpɔ́n mì",
          },
          {
            type: "match",
            prompt: "Associe l'ordre",
            pairs: [
              { fr: "Regarde-le", fon: "Kpɔ́n ɛ̀" },
              { fr: "Prends-le", fon: "Zě ɛ̀" },
              { fr: "Mange-le", fon: "Ɖú ì" },
              { fr: "Regarde-moi", fon: "Kpɔ́n mì" },
            ],
          },
          {
            type: "translate",
            prompt: "Traduire en Fon",
            from: "Prends-le.",
            to: "fon",
            answer: "Zě ɛ̀",
            choices: ["Zě ɛ̀", "Yí ɛ̀", "Kpɔ́n ɛ̀", "Ɖú ɛ̀"],
          },
          {
            type: "order",
            prompt: "Reconstruis",
            french: "Mange-le.",
            words: ["Ɖú", "ì"],
            answer: ["Ɖú", "ì"],
          },
          {
            type: "choice",
            prompt: "Sens",
            question: "« Kpɔ́n ɛ̀ » signifie…",
            options: ["Regarde-le", "Regarde-moi", "Regardez-nous", "Il regarde"],
            answer: "Regarde-le",
          },
          {
            type: "match",
            prompt: "Pronom complément",
            pairs: [
              { fr: "moi (COD)", fon: "mì" },
              { fr: "le / lui", fon: "ɛ̀" },
              { fr: "le (variante)", fon: "ì" },
              { fr: "nous", fon: "mǐ" },
            ],
          },
        ],
      },
      {
        id: "w6l4",
        title: "Passé : J'ai regardé",
        emoji: "🕰️",
        exercises: [
          {
            type: "choice",
            prompt: "Conjugaison",
            question: "« J'ai regardé » se dit…",
            options: ["Un kpɔ́n", "À kpɔ́n", "É kpɔ́n", "Mǐ kpɔ́n"],
            answer: "Un kpɔ́n",
            hint: "Le verbe ne change pas, seul le pronom marque la personne.",
          },
          {
            type: "match",
            prompt: "Associe les personnes",
            pairs: [
              { fr: "J'ai regardé", fon: "Un kpɔ́n" },
              { fr: "Tu as regardé", fon: "À kpɔ́n" },
              { fr: "Il a regardé", fon: "É kpɔ́n" },
              { fr: "On a regardé", fon: "È kpɔ́n" },
            ],
          },
          {
            type: "match",
            prompt: "Associe (pluriel)",
            pairs: [
              { fr: "Nous avons regardé", fon: "Mǐ kpɔ́n" },
              { fr: "Vous avez regardé", fon: "Mi kpɔ́n" },
              { fr: "Ils ont regardé", fon: "Yě kpɔ́n" },
              { fr: "C'est lui qui a regardé", fon: "É kpɔ́n wɛ̀" },
            ],
          },
          {
            type: "translate",
            prompt: "Traduire en Fon",
            from: "Vous avez regardé.",
            to: "fon",
            answer: "Mi kpɔ́n",
            choices: ["Mi kpɔ́n", "Mǐ kpɔ́n", "Yě kpɔ́n", "À kpɔ́n"],
          },
          {
            type: "order",
            prompt: "Reconstruis",
            french: "Ils ont regardé.",
            words: ["Yě", "kpɔ́n"],
            answer: ["Yě", "kpɔ́n"],
          },
          {
            type: "choice",
            prompt: "Nuance",
            question: "« É kpɔ́n mi » signifie…",
            options: [
              "Il vous a regardés",
              "Il m'a regardé",
              "Vous l'avez regardé",
              "Il a regardé hier",
            ],
            answer: "Il vous a regardés",
          },
        ],
      },
    ],
  },
];

export const allLessons = worlds.flatMap((w) =>
  w.lessons.map((l) => ({ ...l, worldId: w.id, worldTitle: w.title, color: w.color }))
);

export function getLesson(id: string) {
  for (const w of worlds) {
    const l = w.lessons.find((x) => x.id === id);
    if (l) return { lesson: l, world: w };
  }
  return null;
}
